### ISSUE TITLE
1.18.2 scoreboard dont work

### ISSUE THREAD

**Issue by VSpier** [ItzStonlex/StonlexAPI#4]
1.18.2 scoreboard dont work
`com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.network.chat.IChatBaseComponent exists in class PacketPlayOutScoreboardTeam.
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:369) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:349) ~[ProtocolLib.jar:?]
	at ru.stonlex.bukkit.scoreboard.BaseScoreboardLine.getTeamPacket(BaseScoreboardLine.java:102) ~[maincore.jar:?]
	at ru.stonlex.bukkit.scoreboard.BaseScoreboardLine.create(BaseScoreboardLine.java:39) ~[maincore.jar:?]
	at ru.stonlex.bukkit.scoreboard.BaseScoreboard.setScoreboardToPlayer(BaseScoreboard.java:92) ~[maincore.jar:?]
	at ru.stonlex.bukkit.scoreboard.BaseScoreboard.setScoreboardScope(BaseScoreboard.java:271) ~[maincore.jar:?]
	at ru.stonlex.bukkit.scoreboard.BaseScoreboardBuilder.build(BaseScoreboardBuilder.java:127) ~[maincore.jar:?]`

same thing with Teams
`com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 2, Size: 1)
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:373) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:349) ~[ProtocolLib.jar:?]
	at ru.stonlex.bukkit.protocollib.team.ProtocolTeam.getTeamPacket(ProtocolTeam.java:136) ~[maincore.jar:?]
	at ru.stonlex.bukkit.protocollib.team.ProtocolTeam.sendPacket(ProtocolTeam.java:182) ~[maincore.jar:?]
	at ru.stonlex.bukkit.protocollib.team.ProtocolTeam.addReceiver(ProtocolTeam.java:194) ~[maincore.jar:?]
	at ru.stonlex.bukkit.protocollib.team.ProtocolTeam.addPlayerEntry(ProtocolTeam.java:215) ~[maincore.jar:?]`

**Comment by VSpier** [comment]
full api dont work with 1.18.2... epic :)
